# 项目相关配置
jianwoo:
  # 名称
  name: Jianwoo
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/jianwoo/uploadPath，Linux配置 /home/jianwoo/uploadPath）
  profile: /www/upload/jianwoo
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8060
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

log:
  base: /zp01/application/dev/log/jianwoo
  filename: jianwoo-b2b-service
  tag: jianwoo|jianwoo-b2b-service
  level:
    root: debug
    springframework: warn
    busi: debug

# 用户配置
user:
  password:
    # 密码最大错误次数z
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    filter: stat,wall,slf4j
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/quest-dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: gulihua
        password: pwd1@GulihuaSql
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: jianwoo
        login-password: jianwoo
      filter:
        slf4j:
          enabled: true
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  rabbitmq:
    host: 127.0.0.11
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true #设置publisher-returns消息成功则会向发布者发送成功，失败时不会将消息丢弃，而是返回给发布者，发布者根据需求处理
    publisher-confirm-type: correlated #开启发布确认模式，
    listener:
      simple:
        prefetch: 10 # 设置qos最大缓存数，预接受10个消息到缓存中
        concurrency: 10 # 处理线程数，可以理解为同一时间处理多少个消息
        max-concurrency: 20

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 300
aes:
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCeC7e7N19Cp+EZdK07fr8lQqfp10wQxG+6P79/N+5Sx59l54+hNyu2k8Zb+fsE8Fv0+jOAWrHqDX27XiNZQIrPO+4BiG7kPedfT1r8woQH6dffvFM1gc05XhDevTweZJutCgHYrHqqGXwM2kVgYhQFig0gD7WxXb9GwS+jUJyeG7/sAQUgh+ZwBxetBfp7QvR4iTbm3qOOA4beWpgPehaiSNqF1LJ5ZjoTKK9EWt12RhA/QhKa+i+nHg1GogClcuAOVXafgzm6VmyGHrGolQ5tP7OC6TciqNNsmcVIFmZ2QxKl7QsGgaf8A4JZyQphHLbryelNWYcY6jquEDNXoNVHAgMBAAECggEAXgpy5P9pu2vRUShP+9rLOgyThV0Kcd+w644LEFPjh3YorqY+nJsLc7Qyj4ALkUDENty50GInAzHL4rV9KxpwficW0+qusTj0d43sggHsNhk6znJswKXfy4bhWugW4a7Twv71YkwfIR/Q5ITsSxGRAErIzI8MeeFic2N4SSEqUBkWe8rBxdY42eZzG76z0sbgg9sfUBnURonUepPjMYCOMEhJsKpH7U2qg5MQdooOZFnxgpINL9Ow4EdfRWsRszBbSjhPyA97kCAYykaH+w4z2pKISfY073yqLZiQ1Pn0+UM+shhH56JF9WtgyfvgzyszxM5aSqJursuF6n1qGqoLgQKBgQD3LYijI6NcM6hPqyaGmtoUu5ZMr6AT9vyWmQSPbW3clxoLTSfExOpwnVlKXFHdryLVcDPw+jwefImwhIFM12qChQ0r6/tCq/R2M2N8Tu0JDyfL6PPaGWwvkbgYkvEsVRSZSalshx8nQtBHsXMal8IdRKHP9i96TgE6mtQF6NPzEQKBgQCjr8iD6SVbJwaznaf/CkZz8+lcrzA/SYXNgEkM00kEwiqRnHyOLVf/Ow7jcEA3RhkiTkHWTfEVeRe2nJ1IBcsjnjaop2d8KojfR0KwyKpdfO6iAvPE08NJKuABHtikiWBQaeY6h52ndSdsnqRGhtAyCNOaZcJy/Chilgk7HQCS1wKBgHouJMtXU2nBEyKGXF3O75ut+iZf7cXQoZyjeLCZC+QtQK9zbQQDvkr6TGfIaKMm7hYJB3PHja4YK0t4xB1CoiBwOkmKtUGIlCdVUYjhzqNavXY66UbWqDZ/Vju3bsVWLP90fO3rgMe8bA30NgxgFZC4GzAb5e4T3uGkJMfjBdmxAoGAMSAvqM9PQ9UpoLyfT97wmBpLHmMBsuzI+I0Y332F+6SejAcQJsebEmHSLRZiX3RtVKtx/PR1d4FZSZglaBk9B1qTgviDCXPmkkRb0pzW7KnzILKMILWBdbMleZCdanxEaL3vt/89pKV3iJTwLq6FS470mvERc9sT78qhyJkCtA8CgYEAsGldl0nAnlGCcvMbpoxHIE77VIm9vorNoDlNA7exxYcvy5kxm+5jFUh/7B47KWEY87pNqPDj7yZxbUQFP7xrwtZiyXgc3Q94tAp7E6hnqDYaOo24RtyY6WFacm0BCCqBIE0M8LYdO7Q34BN6ZElxV2aeuY8y/r4pqLzFTv4NWFU=

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cn.jianwoo.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.jianwoo.web.controller
  default-flat-param-object: false
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  basic:
    enable: false
    username: admin
    password: admin

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

redis:
  prefix: test
mq:
  queue:
    task_name: jianwoo.biz.task.queue.test
    dead_name: jianwoo.biz.task.queue.dead.test
    delayed_name: jianwoo.biz.task.queue.delayed.test
exception:
  email:
    subject-prefix: test



